---
version: "2"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
        #      - TZ=<timezone>
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/deluge:/config
      - /mnt/data/torrents:/downloads
    restart: unless-stopped
