---

- name: ensure cron exists
  template:
    src: cron.j2
    dest: "/var/spool/cron/crontabs/{{username}}"  
    owner: "{{username}}"

- name: update default shell
  user: 
    name: "{{username}}"
    shell: /bin/zsh

- name: Ensure paths exist
  file:
    path: "{{item}}"
    owner: "{{username}}"
    state: directory
  ignore_errors: yes #needed for rclone mounts
  with_items:
    - "/mnt/storage" #rclone mount
    - "/mnt/gdrive" #rclone mount
    - "/mnt/gstorage" #rclone mount
    - "{{flexget_path}}"
    - "{{mnt_dir}}/torrents/completed"
    - "{{mnt_dir}}/torrents/TV"
    - "{{mnt_dir}}/torrents/Movies"
    - "{{mnt_dir}}/torrents/Music"
    - "{{mnt_dir}}/torrents/Seed"
    - "{{mnt_dir}}/TV"
    - "{{mnt_dir}}/completed/TV"
    - "{{mnt_dir}}/TV_4K"
    - "{{mnt_dir}}/completed/TV_4K"
    - "{{mnt_dir}}/Movies_4K"
    - "{{mnt_dir}}/completed/Movies_4K"
    - "{{mnt_dir}}/Movies"
    - "{{mnt_dir}}/completed/Movies"
    - "{{data_dir}}/TV"
    - "{{data_dir}}/TV_4K"
    - "{{data_dir}}/Movies_4K"
    - "{{data_dir}}/Movies"
    - "{{data_dir}}/completed/Movies"

- name: Copy flexget config
  copy:
    src: "{{playbook_dir}}/files/flexget"
    dest: "/opt"
    owner: "{{username}}"
    force: yes
    directory_mode: yes

- name: Install flexget
  pip:
    name: flexget
    virtualenv: "{{flexget_path}}/venv"
    #    virtualenv_python: python3.5
  become_user: "{{username}}"

- name: Ensure default folders exist
  file:
    path: "/home/{{username}}/{{item}}"
    owner: "{{username}}"
    group: "{{username}}"
    state: directory
  with_items:
    - torrents/
    - .config/rclone/
 
- name: Ensure torrent folders exist
  file:
    dest: "/home/{{username}}/torrents/{{item}}"
    src: "{{mnt_dir}}/torrents/{{item}}"
    owner: "{{username}}"
    group: "{{username}}"
    state: link
    force: yes
  with_items:
    - completed
    - Movies
    - Music
    - Seed
    - TV

# rclone

- name: Copy systemd config
  copy:
    src: "{{playbook_dir}}/files/systemd/{{item}}.service"
    dest: "/etc/systemd/system/{{item}}.service"
  with_items:
    - rclone
    - rclone-gcache
    - rclone-gdrive

- name: copy rclone conf local
  copy:
    src: "{{playbook_dir}}/files/rclone.conf" 
    dest: "/home/{{username}}/.config/rclone/rclone.conf"
    owner: "{{username}}"
    force: yes

- name: copy rclone conf
  copy: 
    src: "{{playbook_dir}}/files/rclone.conf"
    dest: "/etc/rclone.conf"
    owner: root
    force: yes

- name: reload systemd
  systemd: daemon_reload=yes

- name: enable systemd items
  systemd:
    name: "{{item}}.service"
    enabled: yes
    state: started
  with_items:
    - rclone
    - rclone-gcache
    - rclone-gdrive
