---

- name: ensure cron exists
  template:
    src: cron.j2
    dest: "/var/spool/cron/crontabs/{{username}}"  
    owner: "{{username}}"

- name: update default shell
  user: 
    name: "{{username}}"
    shell: /bin/zsh

- name: Ensure paths exist
  file:
    path: "{{item}}"
    owner: "{{username}}"
    state: directory
  with_items:
    - "{{flexget_path}}"
    - /media/Storage/
    - "{{data_dir}}/torrents/rtorrent/completed"
    - "{{data_dir}}/torrents/rtorrent/TV"
    - "{{data_dir}}/torrents/rtorrent/Movies"
    - "{{data_dir}}/torrents/rtorrent/Music"
    - "{{data_dir}}/torrents/rtorrent/Seed"

- name: Copy flexget config
  copy:
    src: "{{playbook_dir}}/files/flexget"
    dest: "/opt"
    owner: "{{username}}"
    force: yes
    directory_mode: yes

- name: Install flexget
  pip:
    name: flexget
    virtualenv: "{{flexget_path}}/venv"
    virtualenv_python: python3.5
  become_user: "{{username}}"

- name: Ensure rtorrent folders exist
  file:
    src: "/home/{{username}}/torrents/rtorrent/{{item}}"
    dest: "{{data_dir}}/torrents/rtorrent/{{item}}"
    owner: "{{username}}"
    group: "{{username}}"
    state: link
    force: yes
  with_items:
    - completed
    - Movies
    - Music
    - Seed
    - TV

- name: Copy zshrc config
  file:
    src: "{{playbook_dir}}/files/zshrc"
    dest: "/home/{{username}}/.zshrc"
    owner: "{{username}}"
    state: link
    force: yes
  
# iplayer

- name: Copy get_iplayer config
  file:
    src: "{{playbook_dir}}/files/get_iplayer"
    dest: "/home/{{username}}/.get_iplayer"
    owner: "{{username}}"
    state: link
    force: yes

# rclone
- name: Copy systemd config
  copy:
    src: "{{playbook_dir}}/files/systemd/rclone.service"
    dest: /etc/systemd/system/rclone.service

- name: reload systemd
  systemd: daemon_reload=yes

- name: copy rclone conf
  copy: 
    src: "{{playbook_dir}}/files/rclone.conf"
    dest: "/etc/rclone.conf"
    owner: "{{username}}"
    force: yes

- name: enable rclone
  systemd:
    name: rclone
    enabled: yes
    state: started
