---
version: "2.1"
services:
  jackett:
    image:  lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
networks:
  default:
    external:
      name: dockerjackett_default
