version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: zoneminderhq/zoneminder:latest-ubuntu18.04
        restart: unless-stopped
        ports:
            - 80:80
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-Europe/London}
        volumes:
            - /opt/zm/events:/var/cache/zoneminder/events
            - /opt/zm/images:/var/cache/zoneminder/images
            - mysql:/var/lib/mysql
            - logs:/var/log/zoneminder
volumes:
#  events:
#  images:
  mysql:
  logs:
