version: "3"
services:
 privoxyvpn:
  image: binhex/arch-privoxyvpn
  container_name: privoxyvpn-lon
  cap_add:
   - NET_ADMIN
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /opt/privoxyvpn-lon:/config
  environment:
     - VPN_ENABLED=yes 
     - VPN_PROV=custom
     - LAN_NETWORK=192.168.1.0/24 
     - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1 \
       #     - SOCKS_USER=admin 
       #   - SOCKS_PASS=socks 
     - ENABLE_SOCKS=yes 
     - ENABLE_PRIVOXY=yes 
     - DEBUG=true
     - UMASK=000 
     - PUID=0 
     - PGID=0 
  ports:
   - 9118:8118
   - 9119:9118
