tasks:
  sort-tv:
    disable: retry_failed
    filesystem:
      path: /mnt/data/completed/TV
      recursive: yes
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    seen: local
    thetvdb_lookup: yes
    metainfo_series: yes
    require_field: [tvdb_series_name, series_id]
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    regexp:
      reject:
        - sample
        - 2160p
    move:
      # this is where the series will be put
      to: /var/data/TV/{{ tvdb_series_name }}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      rename: "{{ tvdb_series_name|default(series_name) }} - {{ tvdb_ep_id|default(series_id, True) }} - {{ tvdb_ep_name|default('Unknown') }} - {{ quality|upper }}{{ location | pathext }}"
#    exec:
#      on_output:
#        for_accepted: echo "downloaded file {{output}}" >> file
#    notify:
#      task:
#       via:
#         - email:
#             from: bot@copeland.me.uk
#             to: ben.comobile@gmail.com
#             smtp_host: mail.copeland.me.uk
#             smtp_username: bot@copeland.me.uk
#             smtp_password: 
#             smtp_port: 587
#             smtp_tls: yes
