---
version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/jackett:/config
      - /mnt/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
