---
version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /opt/radarr:/config
      - /mnt/storage/Plex/Movies:/movies
      - /mnt/data/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
