---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /opt/sonarr:/config
      - /mnt/storage/Plex/TV:/mnt/storage/Plex/TV
      - /mnt/data/torrents:/downloads
      - /mnt/data/torrents/completed:/data/completed
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  default:
    external:
      name: dockerdeluge_default
